name: QA Dynamic Java Runner (Xray Status Update)

on:
  push:
    branches: [ "tests/**", "main" ]
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout QA Repo
        uses: actions/checkout@v4

      - name: 2. Clonar y Levantar Hospital
        run: |
          git clone -b develop https://github.com/SkySwan0807/GestionHospital_BackEnd.git ./backend
          git clone https://github.com/frontEnd-UPB/GPI-Frontend.git ./frontend
          cd backend && pip install -r requirements.txt
          nohup uvicorn app.main:app --host 0.0.0.0 --port 8000 &
          cd ../frontend && npm install
          npm run dev &
          sleep 30 

      - name: 3. Ejecutar Tests de Java
        id: maven_test
        run: mvn test
        continue-on-error: true 

      - name: 4. Actualizar Estado de Xray
        if: always()
        run: |
          # Extraer el ID de la rama (ej. QA-213)
          TICKET_ID=$(echo "${{ github.ref_name }}" | grep -oE '[A-Z]+-[0-9]+' || true)
          
          # Autenticación
          AUTH=$(echo -n "${{ secrets.JIRA_USER }}:${{ secrets.JIRA_TOKEN }}" | base64)
          
          # Encontrar el archivo de reporte
          REPORT_FILE=$(find target/surefire-reports -name "TEST-*.xml" | head -n 1)

          echo "Subiendo reporte $REPORT_FILE al Test Execution $TICKET_ID..."

          # USAR ESTE COMANDO ESPECÍFICO:
          curl -v \
               -H "Authorization: Basic $AUTH" \
               -H "Content-Type: application/xml" \
               --data-binary @"$REPORT_FILE" \
               "https://${{ secrets.JIRA_DOMAIN }}/rest/raven/1.0/import/execution/junit?testExecKey=$TICKET_ID"
